<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$order = $block->getOrder();
?>
<div class="message message-notice">
    <div class="message-inner">
        <div class="message-content"><?= $block->escapeHtml(__('Changing delivey information will not recalculate shipping, tax or other order amount.')) ?></div>
    </div>
</div>

<fieldset class="fieldset admin__fieldset-wrapper">
    <legend class="legend admin__legend">
        <span><?= $block->escapeHtml($block->getHeaderText()) ?></span>
    </legend>
    <br>
    <div class="form-inline">
        <?= $block->getForm()->toHtml() ?>
    </div>

</fieldset>
